site:
  site_name: 成都博康生物医药有限公司
  site_domain: www.cdbokang.com
  site_email: master@cdbokang.com
  site_phone: 400-123-800
  admin_email: admin@cdbokang.com
  admin_confirm_email: cdbokang@gmail.com
meta:
  keywords: 保健品,鹿茸, 灵芝,人参,虫草,鹿茸灵芝胶囊
  description: 成都市博康生物药业有限公司, 主营鹿茸、灵芝、人参、虫草等名贵保健品，产品鹿茸灵芝胶囊对于增强免疫力，提高缺氧耐受力，具有尤为突出的神奇效果
menu:
    about:
      title: '关于我们'
      menu_match: 'about'
    news:
      title: 企业动态
      menu_match: news
    ensure:
      title: 招商加盟
      menu_match: 'ensure'
    product:
      title: 产品介绍
      menu_match: 'product'
    contact:
      title: 联系我们
      menu_match: 'contact'
    comment:
      title: 雁过留声
      menu_match: 'comment'